### PR TITLE
feat: use cryptographically strong random number generation method

### PR DESCRIPTION
**Pull request by shoter**
Currently in order to verify signature we are using weak photographically random number generator `Random`. It is troublesome for projects that are using static software analysis and this is caught in the library scan. For example Veracode mark usage of `Random` as this library vulnerability.

In order to mitigate that it is better to use [RandomNumberGenerator.GetBytes Method](https://docs.microsoft.com/en-us/dotnet/api/system.security.cryptography.randomnumbergenerator.getbytes?view=net-5.0#System_Security_Cryptography_RandomNumberGenerator_GetBytes_System_Byte___). If we read method description:

> Fills an array of bytes with a cryptographically strong random sequence of values.

We can clearly see that this approach is going to be superior to the former approach.

### CODE REVIEW

**Comment by BeigeBox** [comment]
@rcmstark @LucasSte @childish-sambino @matheuscferraz Just pinging contributors to see if we can get this PR approved & merged.

**Comment by khaosans** [comment]
Was there any outstanding concerns regarding this fix?  Please review and merge if that's possible.  That would be greatly appreciated.

**Comment by BeigeBox** [comment]
I hate to be a nag, but it's been close to 2 months now.  @rcmstark @LucasSte @childish-sambino @matheuscferraz

**Comment by lukasz-xfaang** [comment]
@cdottori-stark , it's been more than 2 months since this PR was opened and there is still no reaction from your team. Could you please take a look at this issue?

**Comment by cdottori-stark** [comment]
Hey guys, sorry for the huge delay. For some reason we stopped receiving the PR notifications from GitHub. I'll take a look at this PR right now.

**Review by cdottori-stark — APPROVED** [review]

**Pull request merged**
